@baseUrl = http://localhost:3000

#
### Mode Development or Production
GET {{baseUrl}}/

# 
### List All Notes
GET {{baseUrl}}/notes/?limit=11&offset=11
### List Single Note
GET {{baseUrl}}/notes/18/

### Create Note
POST {{baseUrl}}/notes/
Content-Type: application/json

  {
    "text": "New note de test",
    "fromId": 16,
    "toId": 17
  }


### Update Note
PATCH {{baseUrl}}/notes/20/
Content-Type: application/json

  {
    "text": "UPDATE bla bla",
    "read": true
  }

### Delete Note
DELETE {{baseUrl}}/notes/2/



#


### List All People
GET {{baseUrl}}/people/?limit=11&offset=11
### List Single Person
GET {{baseUrl}}/people/2/

### Create Person
POST {{baseUrl}}/people/
Content-Type: application/json

  {
    "email": "Joana@gmail.com",
    "password": "Senha1@",
    "name": "Joana"
  }


### Update Person
PATCH {{baseUrl}}/people/12/
Content-Type: application/json

  {
    "password": "Update456@",
    "name": "Fulano Update"
  }

### Delete Person
DELETE {{baseUrl}}/people/15/