services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"

  postgres:
    image: bitnami/postgresql:14.15.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=crud_nestjs
    volumes:
      - postgres_crud_nestjs:/bitnami/postgresql

volumes:
  postgres_crud_nestjs:      
  