services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"

  postgres:
    image: bitnami/postgresql:14.15.0
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud_nestjs
    volumes:
      - postgres:/data/db

volumes:
  postgres:      
  